import React, { useState } from "react";
import Print from "./Print";

export default function Array() {
  const studentArray = [
    {
      name: "Sachin",
      age: 19,
      stand: 10,
      city: "Nashik",
      state: "Maharastra",
      school: "HSC",
      gender: "male",
    },
    {
      name: "Anurag",
      age: 22,
      stand: 9,
      city: "Pune",
      state: "Maharastra",
      school: "HSC",
      gender: "male",
    },
    {
      name: "Abhishek",
      age: 23,
      stand: 12,
      city: "Nashik",
      state: "Maharastra",
      school: "HSC",
      gender: "male",
    },
    {
      name: "Richa",
      age: 21,
      stand: 10,
      city: "Patna",
      state: "Bihar",
      school: "HSC",
      gender: "female",
    },
    {
      name: "Riya",
      age: 18,
      stand: 11,
      city: "Kolkata",
      state: "Bengal",
      school: "HSC",
      gender: "female",
    },
    {
      name: "Akash",
      age: 28,
      stand: 15,
      city: "Lucknow",
      state: "UP",
      school: "HSC",
      gender: "male",
    },
    {
      name: "Sushil",
      age: 26,
      stand: 10,
      city: "Lucknow",
      state: "UP",
      school: "HSC",
      gender: "male",
    },
    {
      name: "Dipti",
      age: 20,
      stand: 11,
      city: "Ahemdabad",
      state: "Gujarat",
      school: "HSC",
      gender: "female",
    },
    {
      name: "Ajay",
      age: 25,
      stand: 11,
      city: "Patna",
      state: "Bihar",
      school: "HSC",
      gender: "male",
    },
    {
      name: "Prachi",
      age: 19,
      stand: 10,
      city: "Patna",
      state: "Bihar",
      school: "HSC",
      gender: "female",
    },
    {
      name: "Gravit",
      age: 29,
      stand: 10,
      city: "Nashik",
      state: "Maharastra",
      school: "HSC",
      gender: "male",
    },
    {
      name: "Vandana",
      age: 19,
      stand: 10,
      city: "Pune",
      state: "Maharastra",
      school: "HSC",
      gender: "female",
    },
    {
      name: "Avrodip",
      age: 22,
      stand: 10,
      city: "Patna",
      state: "Bihar",
      school: "HSC",
      gender: "male",
    },
    {
      name: "Nishu",
      age: 19,
      stand: 10,
      city: "Patna",
      state: "Bihar",
      school: "HSC",
      gender: "female",
    },
    {
      name: "Shubham",
      age: 27,
      stand: 10,
      city: "Pune",
      state: "Maharastra",
      school: "HSC",
      gender: "male",
    },
    {
      name: "Saurabh",
      age: 22,
      stand: 10,
      city: "Ahemdabad",
      state: "Gujarat",
      school: "HSC",
      gender: "male",
    },
    {
      name: "Nikki",
      age: 19,
      stand: 10,
      city: "Nashik",
      state: "Maharastra",
      school: "HSC",
      gender: "female",
    },
    {
      name: "Aman",
      age: 20,
      stand: 10,
      city: "Nashik",
      state: "Maharastra",
      school: "HSC",
      gender: "male",
    },
    {
      name: "Depali",
      age: 25,
      stand: 10,
      city: "Lucknow",
      state: "UP",
      school: "HSC",
      gender: "female",
    },
    {
      name: "Rohit",
      age: 20,
      stand: 10,
      city: "Nashik",
      state: "Maharastra",
      school: "HSC",
      gender: "male",
    },
    {
      name: "Rahul",
      age: 19,
      stand: 10,
      city: "Nashik",
      state: "Maharastra",
      school: "HSC",
      gender: "male",
    },
    {
      name: "Madhana",
      age: 19,
      stand: 10,
      city: "Nashik",
      state: "Maharastra",
      school: "HSC",
      gender: "female",
    },
    {
      name: "surya",
      age: 23,
      stand: 10,
      city: "Pune",
      state: "Maharastra",
      school: "HSC",
      gender: "male",
    },
    {
      name: "Raj",
      age: 19,
      stand: 10,
      city: "Nashik",
      state: "Maharastra",
      school: "HSC",
      gender: "male",
    },
    {
      name: "Parshuram",
      age: 19,
      stand: 10,
      city: "Nashik",
      state: "Maharastra",
      school: "HSC",
      gender: "male",
    },
    {
      name: "Ram",
      age: 19,
      stand: 10,
      city: "Nashik",
      state: "Maharastra",
      school: "HSC",
      gender: "male",
    },
    {
      name: "Sachin",
      age: 19,
      stand: 10,
      city: "Nashik",
      state: "Maharastra",
      school: "HSC",
      gender: "male",
    },
  ];
  const [studentList, setStudentList] = useState(studentArray);

  return (
    <div>
      <Print studentList={studentList} setStudentList={setStudentList} />
    </div>
  );
}
